apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: sync-policies
    repoURL: https://github.com/cDevOps80/learn-argocd.git
    targetRevision: main