apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-argocd
spec:
  selector:
    matchLabels:
      app: deploy
  replicas: 1
  template:
    metadata:
      labels:
        app: deploy
    spec:
        containers:
          - name: c1
            image: chaitu1812/nginx:v1.0.0
            ports:
              - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service-argocd
spec:
  type: NodePort
  selector:
    app: deploy
  ports:
    - targetPort: 80
      port: 80
      nodePort: 32047
