apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample
  namespace: argocd
spec:
  project: default
  source:
    chart: nginx
    repoURL: https://github.com/cDevOps80/learn-argocd.git
    targetRevision: main
    path: helm-charts
    helm:
      releaseName: nginx
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default