apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cDevOps80/learn-argocd.git
    targetRevision: main
    path: helm-charts/nginx
    helm:
      releaseName: sample
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default